In [2]:
#Problem 1
import numpy as np
zerovect = [0,0,0,0,1,0,0,0,0,0,]
np.array(zerovect)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [43]:
#Problem 2
bucket = []
for i in range(10,50):
    bucket.append(i)
np.array(bucket)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [70]:
#Problem 3

def reverser(x):
    """Input: Some 1-D Array (Vector)"""
    newvect=[];
    newvect = np.array(x)[::-1]
    return np.array(newvect)
    print(newvect)
    """Output: Reverse of that 1-d Array (Vector)"""


In [91]:
#Problem 4

def find_nonzero(x):
    for index, item in enumerate(np.array(x)):
        if i > 0:
            print(index, item)
testarray= [1,2,0,0,4,0]
find_nonzero(testarray)

0 1
1 2
2 0
3 0
4 4
5 0


In [96]:
#Problem 5

np.random.random_integers(9,size=(3,3))

array([[1, 1, 9],
       [1, 1, 2],
       [8, 6, 2]])

In [137]:
#Problem6
arr2 = np.random.rand(10,10)
arr2[np.argmin(arr2[:, 1]), 0]
arr2[np.argmin(arr2[3:,]), 0]

0.320418020203037

In [149]:
#Problem 7
arr2 = np.random.rand(10)
print(arr2)

[ 0.02579355  0.69028959  0.79152997  0.26643091  0.29880261  0.39710104
  0.88997874  0.9476517   0.99858421  0.22478744]


In [150]:
#Problem 8
np.sort(arr2,axis=0)

array([ 0.02579355,  0.22478744,  0.26643091,  0.29880261,  0.39710104,
        0.69028959,  0.79152997,  0.88997874,  0.9476517 ,  0.99858421])

In [160]:
#Problem 9
arr3 = np.random.rand(9,3,3)

def is_equal(a,b):
"""Checks if arrays have same size, shape, and each element is equal"""
"""Input are two arrays, outputs boolean (not printed) values of 'True' or 'False' """
    return np.array_equal(a,b)
is_equal(arr2, arr3)

False

In [179]:
#Problem 10
prob5array = np.random.ranf(size=(3,3))
print(prob5array)
vecmean1 = prob5array[:1,].mean()
vecmean2 = prob5array[:2,].mean()
vecmean3 = prob5array[:3,].mean()
print(vecmean1)
print(vecmean2)
print(vecmean3)
prob5array[:1,] - vecmean1
prob5array[:2,] - vecmean2
prob5array[:3,] - vecmean3

[[ 0.58290752  0.38725091  0.47211757]
 [ 0.2946722   0.07330839  0.45820776]
 [ 0.85515009  0.54429211  0.64625915]]
0.480758666589
0.378077392974
0.479351744826


array([[ 0.10355577, -0.09210084, -0.00723417],
       [-0.18467954, -0.40604335, -0.02114399],
       [ 0.37579835,  0.06494036,  0.1669074 ]])

In [191]:
#Problem 11
darray1 = np.random.rand(5,5,3)
darray2 = np.random.rand(5,5)
np.multiply(darray1,darray2)

ValueError: operands could not be broadcast together with shapes (5,5,3) (5,5) 

In [213]:
#Problem 12
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = []
newZ = np.array(Z)
for i in range(0,newZ.size - 3):
    R.append((newZ[i:i + 4]))
    print(R)

[array([1, 2, 3, 4])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10]), array([ 8,  9, 10, 11])]
[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10]), array([ 8,  9, 10, 11]), array([ 9, 10, 11, 12])]
[array([1, 2, 3, 4]), 

In [214]:
#Problem 13 - I had to google the conversion from cartesian to polar and found something similar to this
def cart2polar(x, y):
    r = np.sqrt(x**2 + y**2)
    theta = np.arctan2(y, x)
    return(r, theta)

In [218]:
#Problem 14
%time a = np.arange(1024.0).reshape(4, 8, 16, 2)
%time b = np.random.rand(4, 8, 16, 2)
%time sol = a * b

Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns


In [225]:
#Problem 15
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a * b
    

a = np.ones((3, 2))
b = np.ones((3,2)) *3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).any()